### PR TITLE
Remove remaining reference to log4cxx

### PR DESCRIPTION
**Pull request by florent-lamiraux**

### CODE REVIEW

**Comment by bchretien** [comment]
roboptim/roboptim-core-plugin-ipopt#38 merged, I'm re-running the CI build.

**Comment by bchretien** [comment]
The CI build fails because of log4cxx logs that are generated in debug only. These should be removed as well.

**Comment by florent-lamiraux** [comment]
Travis tests fail for reason out of the scope of this pull request:
  - 246.3: The command "pip install --user codecov" failed and exited with 127 during,
  - 246.4: line 4061, failure during compilation of roboptim-core,
  - 246.5: line 6605, failure in system headers,
  - 246.6: The command "pip install --user codecov" failed and exited with 127 during.

As the current master branch does not compile, is it possible to merge this pull request ?

**Comment by bchretien** [comment]
There has been some issues with the OSX build (they removed the IPOPT formula and did not merge it in the core repository...). I haven't succeeded in fixing it for `roboptim-core-plugin-ipopt`, so I'll just ignore the failure here as well. The rest looks fine, thanks!

**Pull request merged**
